steps:
# gitの取得
- name: 'gcr.io/cloud-builders/git'
  args:
  - 'clone'
  - 'https://github.com/kouchanne/SAPAplication.git'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/webcrewsample/frontend'
  - '.'
  env:
  - 'TZ=Asia/Tokyo'
  dir: './frontend'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/webcrewsample/backend'
  - '.'
  env:
  - 'TZ=Asia/Tokyo'
  dir: './backend'

images: ['gcr.io/webcrewsample/frontend','gcr.io/webcrewsample/backend']
